import { SANDBOX_WORKSPACE_ROOT } from "@code-artisan/shared";
import type { E2BSandbox } from "../../sandbox/e2b-sandbox";

const ENV_LOCAL_PATH = `${SANDBOX_WORKSPACE_ROOT}/.env.local`;

export interface SupabaseEnv {
  url: string;
  anonKey: string;
}

export function renderSupabaseEnvLocal(env: SupabaseEnv): string {
  return [
    "# Auto-generated by code-artisan — overwritten on every sandbox start. Do not edit.",
    `VITE_SUPABASE_URL=${env.url}`,
    `VITE_SUPABASE_ANON_KEY=${env.anonKey}`,
    "",
  ].join("\n");
}

export async function writeSupabaseEnvLocal(
  sandbox: E2BSandbox,
  env: SupabaseEnv,
): Promise<void> {
  await sandbox.sdk.files.write(ENV_LOCAL_PATH, renderSupabaseEnvLocal(env));
}
